
#let persons = (
  (type: "person", sex: "m", name: "Ali", emoji: "👨"),
  (type: "person", sex: "m", name: "Jax", emoji: "🫅"),
  (type: "person", sex: "m", name: "Roy", emoji: "👦"),
  (type: "person", sex: "m", name: "Noe", emoji: "👳"),
  (type: "person", sex: "m", name: "Rex", emoji: "👴"),
  (type: "person", sex: "m", name: "Joe", emoji: "🤠"),
  (type: "person", sex: "m", name: "Lee", emoji: "🧟"),
  (type: "person", sex: "m", name: "Ben", emoji: "🧑"),
  (type: "person", sex: "m", name: "Mac", emoji: "🥷"),
  (type: "person", sex: "m", name: "Fox", emoji: "👱"),
  (type: "person", sex: "m", name: "Max", emoji: "🧔"),
  (type: "person", sex: "f", name: "Mei", emoji: "🧒"),
  (type: "person", sex: "f", name: "Eva", emoji: "🫅"),
  (type: "person", sex: "f", name: "Mia", emoji: "👵"),
  (type: "person", sex: "f", name: "Ada", emoji: "👼"),
  (type: "person", sex: "f", name: "Zoe", emoji: "👧"),
  (type: "person", sex: "f", name: "Amy", emoji: "👩"),
  (type: "person", sex: "f", name: "Joy", emoji: "🤖"),
  (type: "person", sex: "f", name: "Noa", emoji: "👶"),
  (type: "person", sex: "f", name: "Lea", emoji: "🧓"),
  (type: "person", sex: "f", name: "Mae", emoji: "🧕"),
  (type: "person", sex: "f", name: "Liv", emoji: "🧚"),
)

#let relations = (
  (type: "relation", article: "a", singular: "sibling", plural: "siblings", emoji: "👧"),
  (type: "relation", article: "a", singular: "brother", plural: "brothers", emoji: "👦"),
  (type: "relation", article: "a", singular: "sister", plural: "sisters", emoji: "👧"),
  (type: "relation", article: "a", singular: "cousin", plural: "cousins", emoji: "👦"),
  (type: "relation", article: "a", singular: "friend", plural: "friends", emoji: "👦"),
  (type: "relation", article: "a", singular: "pet", plural: "pets", emoji: "🐕"),
  (type: "relation", article: "a", singular: "dog", plural: "dogs", emoji: "🐕"),
  (type: "relation", article: "a", singular: "cat", plural: "cats", emoji: "🐈"),
)

#let objects = (
  (type: "object", size: "s", article: "a", singular: "coin", plural: "coins", emoji: "🪙"),
  (type: "object", size: "s", article: "a", singular: "pencil", plural: "pencils", emoji: "✏"),
  (type: "object", size: "s", article: "a", singular: "lightbulb", plural: "lightbulbs", emoji: "💡"),
  (type: "object", size: "s", article: "a", singular: "die", plural: "dice", emoji: "🎲"),
  (type: "object", size: "s", article: "a", singular: "watch", plural: "watches", emoji: "⌚"),
  (type: "object", size: "s", article: "a", singular: "hourglass", plural: "hourglasses", emoji: "⌛"),
  (type: "object", size: "s", article: "a", singular: "tennis ball", plural: "tennis balls", emoji: "🥎"),
  (type: "object", size: "m", article: "a", singular: "camera", plural: "camera", emoji: "📷"),
  (type: "object", size: "m", article: "a", singular: "flashlight", plural: "flashlights", emoji: "🔦"),
  (type: "object", size: "m", article: "a", singular: "trumpet", plural: "trumpets", emoji: "🎺"),
  (type: "object", size: "l", article: "a", singular: "car", plural: "cars", emoji: "🚗"),
  (type: "object", size: "l", article: "a", singular: "tractor", plural: "tractors", emoji: "🚜"),
  (type: "object", size: "l", article: "a", singular: "bus", plural: "buses", emoji: "🚌"),
  (type: "object", size: "l", article: "a", singular: "tram", plural: "trams", emoji: "🚋"),
  (type: "object", size: "l", article: "a", singular: "train", plural: "trains", emoji: "🚂"),
)

#let containers = (
  (type: "container", size: "s", article: "a", singular:"box", plural: "boxes", emoji: "📦"),
  (type: "container", size: "s", article: "a", singular:"bottle", plural: "bottles", emoji: "🍼"),
  (type: "container", size: "s", article: "a", singular:"bag", plural: "bags", emoji: "👜"),
  (type: "container", size: "s", article: "a", singular:"handbag", plural: "handbags", emoji: "👜"),
  (type: "container", size: "s", article: "a", singular:"schoolbag", plural: "schoolbags", emoji: "🎒"),
  (type: "container", size: "s", article: "a", singular:"backpack", plural: "backpacks", emoji: "🎒"),
  (type: "container", size: "s", article: "a", singular:"pouch", plural: "pouches", emoji: "👝"),
  (type: "container", size: "m", article: "a", singular:"cart", plural: "carts", emoji: "🛒"),
  (type: "container", size: "l", article: "a", singular:"circus tent", plural: "circus tents", emoji: "🎪"),
  (type: "container", size: "l", article: "a", singular:"parking lot", plural: "parking lots", emoji: "🅿"),
)

#let edibles = (
  (type: "edible", article: "an", singular: "apple", plural: "apples", emoji: "🍎"),
  (type: "edible", article: "an", singular: "pineapple", plural: "pineapples", emoji: "🍍"),
  (type: "edible", article: "a", singular: "banana", plural: "bananas", emoji: "🍌"),
  (type: "edible", article: "a", singular: "cookie", plural: "cookies", emoji: "🍪"),
  (type: "edible", article: "a", singular: "chocolate bar", plural: "chocolate bars", emoji: "🍫"),
  (type: "edible", article: "a", singular: "French fry", plural: "French fries", emoji: "🍟"),
  (type: "edible", article: "a", singular: "shrimp", plural: "shrimp", emoji: "🦐"),
  (type: "edible", article: "a", singular: "blueberry", plural: "blueberries", emoji: "🫐"),
  (type: "edible", article: "a", singular: "cherry", plural: "cherries", emoji: "🍒"),
  (type: "edible", article: "a", singular: "fish cake", plural: "fish cakes", emoji: "🍥"),
  (type: "edible", article: "a", singular: "fish crackers", plural: "fish cakes", emoji: "🍘"),
  (type: "edible", article: "a", singular: "onigiri", plural: "onigiri", emoji: "🍙"),
  (type: "edible", article: "a", singular: "lemon", plural: "lemons", emoji: "🍋"),
  (type: "edible", article: "a", singular: "chicken leg", plural: "chicken legs", emoji: "🍗"),
)
