version: '3'

tasks:

  build:
    desc: Generate indexes and copy templates to output folder
    cmds:
      - '{{.SHELL}} mkdir -p out/www/'
      - '{{.SHELL}} cp -ar template/ out/www/'
      - deno run --allow-read --allow-write ./ops/gen-source.mjs

  generate:
    desc: Generate Quiz PDF from CSV
    cmds:
      - '{{.SHELL}} mkdir -p out'
      - typst compile --root . template/main.typ out/quiz.pdf

  clean:
    desc: Remove all generated PDFs
    cmds:
      - '{{.SHELL}} find "template" -name *.pdf -type f -delete'
