version: '3'

includes:
  template: ./template/taskfile.yml

vars:
  # Shell workaround.
  SHELL: '{{if eq .OS "Windows_NT"}}wsl{{end}}'

tasks:

  app:build:
    desc: Build the app to out folder
    cmds:
      - '{{.SHELL}} mkdir -p out/www/'
      - '{{.SHELL}} cp -ar app/src/. out/www/'
      - '{{.SHELL}} cp -ar template/ out/www/'

  app:watch:
    desc: Watch the app
    watch: true
    sources:
      - app/src/**/*
    generates:
      - out/www/app.js
    cmds:
      - task: app:build

  app:serve:
    desc: Serve the app (requires serve-handler)
    cmds:
      - task: app:build
      - serve --no-clipboard "out/www/"

  app:build-docker:
    desc: Run the app with Docker
    cmds:
      - docker compose build app

  app:run-docker:
    desc: Run the app with Docker
    cmds:
      - docker compose up -d app

  clean:
    desc: Remove ALL generated files
    cmds:
      - '{{.SHELL}} rm -rf out/'
      - task: template:clean
      - task: app:clean-docker

  app:clean-docker:
    desc: Remove containers
    cmds:
      - docker compose down app
