version: '3'

includes:
  app: ./app/taskfile.yml
  template: ./template/taskfile.yml

vars:
  # Shell workaround.
  SHELL: '{{if eq .OS "Windows_NT"}}wsl{{end}}'

tasks:

  serve:
    desc: Alias for app:serve
    cmds:
      - task: app:serve

  build:
    desc: Build the app to out folder
    cmds:
      - task: template:build
      - task: app:build

  clean:
    desc: Remove ALL generated files
    cmds:
      - '{{.SHELL}} rm -rf out/'
      - task: template:clean
      - task: app:clean-docker
