version: '3'

tasks:

  serve:
    desc: Serve the app for dev
    cmds:
      - deno run --allow-read --allow-net --watch ./ops/serve.ts

  build:
    desc: Build the app and copy templates to output folder
    cmds:
      - '{{.SHELL}} mkdir -p out/www/Quiz-O-Matic/'
      - '{{.SHELL}} cp -ar app/src/. out/www/Quiz-O-Matic/'
      - '{{.SHELL}} cp -ar template/ out/www/Quiz-O-Matic/'

  build-docker:
    desc: Run the app with Docker
    cmds:
      - docker compose -f ops/compose.yml build app

  run-docker:
    desc: Run the app with Docker
    cmds:
      - docker compose up -f ops/compose.yml -d app

  clean-docker:
    desc: Remove containers
    cmds:
      - docker compose -f ops/compose.yml down app
