code = "Q_MAT_EQM"
subject = "mat"
name = "Model collection - 1 unknown equation (multiplication + addition)"
description = "Problem to solve a single unknown equation by applying a multiplication and an addition."
tags = ["practical", "closed_answers", "problem", "plot", "algebra", "equation"]
levelScale = "grades"
supportedLevels = ["g6"]
supportedLengths = ["quick"]

[defaults]
level = "g6"
length = "quick"
