
services:

    app:
        image: quiz-app
        container_name: app
        env_file: ../app/.env
        build:
            context: ../
            dockerfile: app/ops/Dockerfile
        restart: no
        ports:
            #- "${PORT}:80"
            - "3000:80"
